name: DAST Baseline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 2"

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    if: ${{ secrets.STAGING_BASE_URL != '' }}
    steps:
      - name: OWASP ZAP Baseline
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ secrets.STAGING_BASE_URL }}
          rules_file_name: ".zap/rules.tsv"
